services:
  - type: web
    name: git-game
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20
    healthCheckPath: /healthz
